on: [workflow_dispatch]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build
        run: ./gradlew desktop:dist
      - name: Get Release Version
        id: get-version
        run: |
          VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.get-version.outputs.VERSION }}"
          prerelease: true
          title: "v${{ steps.get-version.outputs.VERSION }}"
          files: |
            desktop/build/libs/*.jar

      - name: Increment Version
        run: |
          NEW_VERSION=$(echo '${{ steps.get-version.outputs.VERSION }}' | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e')
          sed -i'.bak' "s/    version = '[^']*'/    version = '$NEW_VERSION'/" build.gradle
          rm build.gradle.bak
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump project version"
          file_pattern: "*.gradle"